/**
 * Underwriting decision memo — a one-page internal PDF filed to the deal at
 * approval time (deal_documents kind 'decision_memo').
 *
 * The signed DLT-APP renders its "FOR DELT CAPITAL USE ONLY" box blank
 * because the application is executed at intake, before terms exist, and a
 * sent envelope is immutable. This memo is the paper record of the decision
 * that box represents; the CRM stays the source of truth.
 *
 * Deno-only (imports pdf-lib).
 */

import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";

export interface DecisionMemoFields {
  merchantName: string;
  applicationId?: string;
  underwriter?: string;
  decision: "Approved" | "Declined";
  decidedAt: string; // YYYY-MM-DD
  approvedAmount?: number;
  factorRate?: number;
  paybackAmount?: number;
  termMonths?: number;
  paymentFrequency?: string;
  holdbackPct?: number;
  tier?: string;
  compositeScore?: number;
  stipulations?: string;
  declineReason?: string;
}

const usd = (n: number | undefined) =>
  n == null ? "—" : n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export async function renderDecisionMemoPdf(f: DecisionMemoFields): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // US Letter
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const navy = rgb(0.043, 0.145, 0.271);
  const gray = rgb(0.35, 0.38, 0.44);

  let y = 740;
  const text = (s: string, opts: { x?: number; size?: number; f?: typeof font; color?: typeof navy } = {}) => {
    page.drawText(s, {
      x: opts.x ?? 48,
      y,
      size: opts.size ?? 10,
      font: opts.f ?? font,
      color: opts.color ?? rgb(0.07, 0.09, 0.13),
    });
  };
  const row = (label: string, value: string) => {
    text(label.toUpperCase(), { size: 7.5, color: gray });
    text(value, { x: 220, size: 10 });
    y -= 20;
  };

  text("DELT CAPITAL", { size: 16, f: bold, color: navy });
  y -= 16;
  text("UNDERWRITING DECISION MEMO — INTERNAL", { size: 9, color: gray });
  y -= 8;
  page.drawLine({ start: { x: 48, y }, end: { x: 564, y }, thickness: 1.5, color: navy });
  y -= 26;

  row("Merchant", f.merchantName);
  row("Application ID", f.applicationId ?? "—");
  row("Underwriter", f.underwriter ?? "—");
  row("Decision date", f.decidedAt);
  y -= 6;

  text(`DECISION: ${f.decision.toUpperCase()}`, {
    size: 13,
    f: bold,
    color: f.decision === "Approved" ? rgb(0.02, 0.45, 0.25) : rgb(0.7, 0.12, 0.12),
  });
  y -= 28;

  if (f.decision === "Approved") {
    row("Approved amount", usd(f.approvedAmount));
    row("Factor rate", f.factorRate != null ? String(f.factorRate) : "—");
    row("Purchased amount (payback)", usd(f.paybackAmount));
    row("Term", f.termMonths != null ? `${f.termMonths} months (est.)` : "—");
    row("Payment frequency", f.paymentFrequency ?? "Daily");
    row("Holdback / remittance", f.holdbackPct != null ? `${f.holdbackPct}%` : "—");
    row("Tier", f.tier ?? "—");
    row("Composite score", f.compositeScore != null ? String(f.compositeScore) : "—");
  } else {
    row("Decline reason", f.declineReason ?? "—");
  }
  y -= 6;

  text("STIPULATIONS / NOTES", { size: 7.5, color: gray });
  y -= 14;
  const stips = (f.stipulations ?? "None.").split("\n");
  for (const line of stips.slice(0, 12)) {
    text(line.slice(0, 110), { size: 9.5 });
    y -= 14;
  }

  y = 60;
  text(
    "Generated by the Delt CRM at decision time. Pairs with the signed Form DLT-APP, whose decision box is intentionally blank.",
    { size: 7, color: gray },
  );

  return await doc.save();
}
