import { createClient } from '@supabase/supabase-js';
import { projectId, publicAnonKey } from '/utils/supabase/info';

// Prefer environment variables (set in .env.local locally and in Vercel),
// falling back to the committed autogenerated info.tsx so the app still
// builds in environments where the env vars are not provided.
const envUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

const supabaseUrl = envUrl || `https://${projectId}.supabase.co`;
const supabaseAnonKey = envAnonKey || publicAnonKey;

// Singleton Supabase client for the frontend. Sessions persist so a signed-in
// user stays authenticated across reloads (used to gate the /dashboard CRM).
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Base URL for the Hono edge function server
export const serverBaseUrl = `${supabaseUrl}/functions/v1/make-server-940653c6`;

// Helper for making authenticated API calls to the server
export async function serverFetch(
  route: string,
  options: RequestInit = {}
): Promise<Response> {
  const url = `${serverBaseUrl}${route.startsWith('/') ? route : `/${route}`}`;
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    Authorization: `Bearer ${supabaseAnonKey}`,
    ...(options.headers as Record<string, string> || {}),
  };
  return fetch(url, { ...options, headers });
}
