import { createClient } from '@supabase/supabase-js';
import { projectId, publicAnonKey } from '/utils/supabase/info';

// Prefer environment variables (set in .env.local locally and in Vercel),
// falling back to the committed autogenerated info.tsx so the app still
// builds in environments where the env vars are not provided.
const envUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

const supabaseUrl = envUrl || `https://${projectId}.supabase.co`;
const supabaseAnonKey = envAnonKey || publicAnonKey;

// Singleton Supabase client for the frontend. Sessions persist so a signed-in
// user stays authenticated across reloads (used to gate the /dashboard CRM).
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Base URL for the Hono edge function server
export const serverBaseUrl = `${supabaseUrl}/functions/v1/make-server-940653c6`;

// Factory for staff-authenticated calls to the Hono edge server. Every route
// on the server goes through requireUser(), so the signed-in user's JWT (not
// the anon key) must be attached per call. Each store binds its own prefix:
//   const authFetch = makeAuthFetch('/plaid', 'You must be signed in …');
export function makeAuthFetch(basePath: string, signInMessage: string) {
  return async function authFetch(route: string, options: RequestInit = {}): Promise<any> {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (!token) throw new Error(signInMessage);
    const url = `${serverBaseUrl}${basePath}${route.startsWith('/') ? route : `/${route}`}`;
    const res = await fetch(url, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
        ...((options.headers as Record<string, string>) || {}),
      },
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok || json?.ok === false) {
      throw new Error(json?.error || `Request failed (${res.status})`);
    }
    return json;
  };
}
